### PR TITLE
Update ci-build and fix fsharp project

### PR DESCRIPTION
**Pull request by SKProCH**

### CODE REVIEW

**Comment by SKProCH** [comment]
@maxkatz6 can you review, please?

**Review by maxkatz6 — APPROVED** [review]

**Comment by SKProCH** [comment]
@maxkatz6 can you publish a new release, please? Seems like this is not automatic

**Comment by maxkatz6** [comment]
I think nuget page is owned by @worldbeater

**Comment by worldbeater** [comment]
@SKProCH Live.Avalonia 1.4 is on its way to NuGet now :ship:
https://github.com/AvaloniaUI/Live.Avalonia/actions/runs/6243733441
See also: https://github.com/AvaloniaUI/Live.Avalonia/releases
And: https://www.nuget.org/packages/Live.Avalonia/1.4.1

**Pull request merged**
